name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ec2-user/trial/CICDTest &&
            sudo yum -y update &&
            sudo yum install -y httpd &&
            sudo systemctl start httpd &&
            sudo systemctl enable httpd &&
            sudo yum install nodejs npm -y &&
            npm install &&
            sudo npm run build &&
            cd build &&
            sudo rm -rf /var/www/html/reactapp5/* &&
            sudo mv * /var/www/html/reactapp5 &&
            sudo systemctl restart httpd
          '
